// Routes for all roles are defined here once.
// Do not edit this file to work on a page: work inside pages/<role>/.
import { Route, Routes, useMatch } from 'react-router-dom'
import AppNavbar from './components/AppNavbar.jsx'
import HomePage from './pages/HomePage.jsx'
import NotFoundPage from './pages/NotFoundPage.jsx'
import CustomerPage from './pages/customer/CustomerPage.jsx'
import OfficerPage from './pages/officer/OfficerPage.jsx'
import BoardPage from './pages/board/BoardPage.jsx'

function App() {
  // The display board is full screen (team decision): no navbar there.
  // useMatch follows the route rules, so '/board/' is matched too.
  const showNavbar = useMatch('/board') === null

  return (
    <>
      {showNavbar && <AppNavbar />}
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/customer" element={<CustomerPage />} />
        <Route path="/officer" element={<OfficerPage />} />
        <Route path="/officer/:counterId" element={<OfficerPage />} />
        <Route path="/board" element={<BoardPage />} />
        <Route path="*" element={<NotFoundPage />} />
      </Routes>
    </>
  )
}

export default App
